name: seedsaver_wallet
description: Demonstrates how to use the flutter_zxing plugin.
version: 0.0.1
publish_to: "none" # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_credit_card: ^3.0.1 
  english_words: ^4.0.0
  provider: ^6.0.0
  flutter_zxing: ^1.1.1

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
