name: seedsaver_wallet
description: Scan and displys qrs.
version: 0.0.1
publish_to: "none" # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_credit_card: ^3.0.1 
  provider: ^6.0.0
  image: ^4.0.15
  base32: ^2.1.3
  path_provider: ^2.0.13
  share: ^2.0.4
  file_picker: ^5.2.5
  cryptography: ^2.5.0
  qr_flutter: ^4.0.0
  hex: ^0.2.0
  flutter_launcher_icons: ^0.12.0
  chia_crypto_utils: ^1.0.16
  flutter_riverpod: ^2.3.2
  flutter_svg: ^2.0.4
  clipboard: ^0.1.3
  flutter_dotenv: ^5.0.2
  web3dart: ^2.4.1
  url_launcher: ^6.1.10
  flutter_zxing: ^1.1.2
  convert: ^3.0.2


dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo_only.png"


  
